# Considering code

In [23]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

# ANSWER 1
YES

In [24]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


# ANSWER 2

In [25]:
print("Data types of elements in 'list_':")
for element in list_:
    print(type(element))

print("\nData types of elements in 'array_list':")
for element in array_list:
    print(type(element))

Data types of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# ANSWER 3
Yes, there will be a difference in the data type of the elements present in both variables, list_ and array_list

In [26]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in 'list_':")
for element in list_:
    print(type(element))

print("\nData types of elements in 'array_list':")
for element in array_list:
    print(type(element))

Data types of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Considering code

In [28]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_list)
print(num_array)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


# ANSWER 4

In [29]:
num_array.shape

(2, 3)

In [30]:
num_array.size

6

# ANSWER 5

In [31]:
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# ANSWER 6

In [32]:
identity_matrix = np.identity(5, dtype="int")
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
